### ISSUE TITLE
Implementation of Exponential Search

### ISSUE THREAD

**Issue by Vishal1003** [Vishal1003/Algorithms#16]
Documentation of Exponential Search algorithm required

**Comment by gaurav1912** [comment]
I want to work on this issue.

**Comment by Vishal1003** [comment]
@gaurav1912 yes you can contribute.

**Comment by gaurav1912** [comment]
I've created a pr. Kindly merge that. Thanks for this opportunity.

**Comment by Vishal1003** [comment]
@gaurav1912 I've merged your request!
