### ISSUE TITLE
Documentation and Implementation of Flood fill Algorithm

### ISSUE THREAD

**Issue by Vishal1003** [Vishal1003/Algorithms#38]
Implement Flood Fill Algorithm in Java/Cpp and explain the algorithm (proper documentation).

Note : 
1. The code should be well commented so that anyone can understand that. 
2. Proper documentation should be provided (either edit the readme or create a new md file and add a link in the readme file under relevant header.

**Comment by sahanihit** [comment]
Can you assign this to me?

**Comment by Vishal1003** [comment]
@sahanihit sure. You can work on this.

**Comment by princekalra** [comment]
can u please assign it to me
