### ISSUE TITLE
Documentation and Implementation of Kadane’s algorithm

### ISSUE THREAD

**Issue by Vishal1003** [Vishal1003/Algorithms#41]
Implement Kadane’s algorithm in Java/Cpp and explain the algorithm (proper documentation).

Note :

The code should be well commented so that anyone can understand that.
Proper documentation should be provided (either edit the readme or create a new md file and add a link in the readme file under relevant header.

**Comment by shubhdeep123** [comment]
i want to work on this please assign me this issue

**Comment by Vishal1003** [comment]
Sure.

**Comment by shubhdeep123** [comment]
@Vishal1003 should i commit changes to different branch or to master? i have sent PR can you review it ?

**Comment by Vishal1003** [comment]
I guess you've closed your pr. Kindly resolve all the conflicts and again create a PR

**Comment by shubhdeep123** [comment]
hey @Vishal1003 i have resolve all conflicts, this is the new PR
