### ISSUE TITLE
Documentation and Implementation of Inorder, Preorder, Postorder Tree Traversals

### ISSUE THREAD

**Issue by Vishal1003** [Vishal1003/Algorithms#48]
Implement Inorder, Preorder, Postorder Tree Traversals in Java/Cpp and explain the algorithm (proper documentation).

Note :

The code should be well commented so that anyone can understand that.
Proper documentation should be provided (either edit the readme or create a new md file and add a link in the readme file under relevant header.

**Comment by AparnaJuhi** [comment]
I want to work on this issue. Please assign it to me

**Comment by Vishal1003** [comment]
sure!

**Comment by iamabhii1** [comment]
I also want to work on this issue .please assign it to me

**Comment by AparnaJuhi** [comment]
@Vishal1003  I have implemented the Tree Traversal Methods with proper comments and documentations. Please review my PR !

**Comment by Vishal1003** [comment]
Merged

**Comment by AparnaJuhi** [comment]
Hi Vishal, You have merged my PR and I have got mail also. But its not
showing in HacktoberFest page. I am new to this HacktoberFest and Open
Source., therefore I have this query. Can you please tell me when it will
show
[image: tree_traversl.jpg]
