### ISSUE TITLE
Documentation and Implementation of Topological Sorting in a DAG

### ISSUE THREAD

**Issue by Vishal1003** [Vishal1003/Algorithms#49]
Implement Topological Sorting in a DAG in Java/Cpp and explain the algorithm (proper documentation).

Note :

The code should be well commented so that anyone can understand that.
Proper documentation should be provided (either edit the readme or create a new md file and add a link in the readme file under relevant header.

**Comment by Harshit564** [comment]
Assign this issue to me @Vishal1003

**Comment by Vishal1003** [comment]
Sure

**Comment by Rituraj-commits** [comment]
Assign this issue to me
