### ISSUE TITLE
Documentation and Implementation of Kruskal’s Algorithm for finding Minimum Spanning Tree

### ISSUE THREAD

**Issue by Vishal1003** [Vishal1003/Algorithms#51]
Implement Kruskal’s Algorithm in Java/Cpp and explain the algorithm (proper documentation).

Note :

The code should be well commented so that anyone can understand that.
Proper documentation should be provided (either edit the readme or create a new md file and add a link in the readme file under relevant header.

**Comment by shubhdeep123** [comment]
Can i work on this too?

**Comment by Vishal1003** [comment]
Yes you can

**Comment by shubhdeep123** [comment]
@Vishal1003  Here is my PR with proper Documentation and implementation of Kruskal's Algo
