### ISSUE TITLE
 Documentation and Implementation of Kruskal’s Algorithm for finding Minimum Spanning Tree

### ISSUE THREAD

**Issue by Vishal1003** [Vishal1003/Algorithms#56]
Implement Kruskal’s Algorithm in Java/Cpp and explain the algorithm (proper documentation).

Note :

The code should be well commented so that anyone can understand that.
Proper documentation should be provided (either edit the readme or create a new md file and add a link in the readme file under relevant header.

**Comment by rishi-1092** [comment]
hey! can you assign me this issue

**Comment by siddharthrajaraja** [comment]
Assign me

**Comment by Harshit564** [comment]
Assign this issue to me @Vishal1003

**Comment by uditascloud** [comment]
Assign me. Thank You

**Comment by siddharthrajaraja** [comment]
@Vishal1003  check out #62

**Comment by siddharthrajaraja** [comment]
@Vishal1003  close this issue.
