### ISSUE TITLE
Documentation and Implementation of Dijkstra’s Algorithm

### ISSUE THREAD

**Issue by Vishal1003** [Vishal1003/Algorithms#57]
Implement Dijkstra’s Algorithm in Java/Cpp and explain the algorithm (proper documentation).

Note :

The code should be well commented so that anyone can understand that.
Proper documentation should be provided (either edit the readme or create a new md file and add a link in the readme file under relevant header.

**Comment by Amitsharma45** [comment]
@Vishal1003 please assign this issues to me.

**Comment by Vishal1003** [comment]
Sure

**Comment by dipanshug124** [comment]
@Vishal1003 please also assign this to me

**Comment by 26Vinayak** [comment]
I would like to work on this issue 
Plzz assign this to me.

**Comment by uditascloud** [comment]
Please assign it to me. Thank you

**Comment by ASHISHCHHABRA1299** [comment]
@Vishal1003 Assign this issue to me. I would be happy to work on this issue.

**Comment by SanyuktaSaha** [comment]
@Vishal1003 Please assign this to me. Thankyou

**Comment by Vishal1003** [comment]
Hello @ASHISHCHHABRA1299 @SanyuktaSaha @dipanshug124 @26Vinayak . This issue was already assigned and can be done by one person only. Meanwhile you can check #93 and contribute.

**Comment by sachdevarobin** [comment]
please assign this issue to me

**Comment by AMorr1** [comment]
please assign it to me i can do it with proper documentation.

**Comment by babitha667** [comment]
I would like to contribute . please assign me the issue.
