### ISSUE TITLE
Documentation and Implementation of Segment Tree

### ISSUE THREAD

**Issue by ankur-kayal** [Vishal1003/Algorithms#61]
Implement Segment Tree in Java/Cpp and explain the algorithm (proper documentation).

Note :

The code should be well commented so that anyone can understand that.
Proper documentation should be provided (either edit the readme or create a new md file and add a link in the readme file under relevant header.

**Comment by ankur-kayal** [comment]
Can i implement this in c++?

**Comment by Vishal1003** [comment]
Sure

**Comment by ankur-kayal** [comment]
Do i implement a simple segment tree ?

**Comment by ankur-kayal** [comment]
Point updates and range queries will do ?

**Comment by Vishal1003** [comment]
Yes. You can implement a simple segment trees (where we can query on particular range and update certain index in logN time)

**Comment by iamabhii1** [comment]
can i implement this  in java ?

**Comment by 26Vinayak** [comment]
i would like to implement this code . plz assign this to  me.

**Comment by ankur-kayal** [comment]
@Vishal1003 Pull request created 👍
