### ISSUE TITLE
Add Documentation of Counting Sort

### ISSUE THREAD

**Issue by Vishal1003** [Vishal1003/Algorithms#7]
### Implementation

**Comment by shahkv95** [comment]
@Vishal1003 Can I work on this issue?

**Comment by Vishal1003** [comment]
@shahkv95  yes, this issue is still open. You can contribute.

**Comment by shahkv95** [comment]
Please check the PR @Vishal1003 .
Thank you for giving this opportunity.

**Comment by Praveen-Sharma00** [comment]
Is it still open ?
