### ISSUE TITLE
Bubble Sort with Documentation 

### ISSUE THREAD

**Issue by siddharthrajaraja** [Vishal1003/Algorithms#70]
@Vishal1003  I am adding Bubble Sort to this repository

**Comment by esla-ahme** [comment]
I can do it

**Comment by zahinekbal** [comment]
@Vishal1003 please assign it to me 
I will give my best ...

**Comment by ASHISHCHHABRA1299** [comment]
@Vishal1003 Assign this issue to me. I would be happy to work on this issue.

**Comment by Darsh-k-Shah** [comment]
Hey! I am working on it, Please assign it to me if possible.

**Comment by Vishal1003** [comment]
@ASHISHCHHABRA1299 @esla-ahme @zahinekbal @Darsh-k-Shah . This issue is already resolved. Meanwhile you can check #93 and contribute there.
