### ISSUE TITLE
Check if a number is prime (Sieve of Earastosthenes)

### ISSUE THREAD

**Issue by siddharthrajaraja** [Vishal1003/Algorithms#73]
@Vishal1003  I am working on this .

**Comment by Badkul77** [comment]
Please assign it to me

**Comment by Harshsngh07** [comment]
Is this issue still open?

**Comment by ASHISHCHHABRA1299** [comment]
@Vishal1003 Assign this issue to me. I would be happy to work on this issue.

**Comment by siddharthrajaraja** [comment]
@Vishal1003  please merge PR #75
