### ISSUE TITLE
Prime Factorising a number in LogN time (Using seive of Eratosthenes)

### ISSUE THREAD

**Issue by ankur-kayal** [Vishal1003/Algorithms#94]
Prime Factorising a number in `O(logN)` in Java/Cpp and explain the algorithm (proper documentation).

Note :

The code should be well commented so that anyone can understand that.
Proper documentation should be provided (either edit the readme or create a new md file and add a link in the readme file under relevant header.

**Comment by ankur-kayal** [comment]
@Vishal1003 can i work on this?

**Comment by Vishal1003** [comment]
It is already implemented. You can work on #93.
