### ISSUE TITLE
DutchNationalFlag Algorithm

### ISSUE THREAD

**Issue by pranavbharadwaj007** [Vishal1003/Algorithms#99]
Helps us to sort the array when there r 3  elements
Problem Link : <a href="https://leetcode.com/problems/sort-colors/" >click to view question</a>
Asked in LeetCode Contest

**Comment by pranavbharadwaj007** [comment]
@Vishal1003 I will be adding this algorithm.

**Comment by Code-Recursion** [comment]
i know this algorithm can i contribute? is'nt this labelled for hacktoberfest?
